### PR TITLE
Milestone2

### PR DESCRIPTION
**Pull request by Ashah15**

### CODE REVIEW

**Comment by Ashah15** [comment]
This is the work for milestone 2 in the calculator react app

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 
**Hello @Ashah15**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] Please make sure that your PR has a Descriptive description and title.
- [ ] in your App component, Please make sure to wrap the elements in a React fragment instead of a div.
 

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Changes Requested 💀 

- [ ] Please make sure you have added a description in your Pull Request before requesting a review. 

Best, 
Arslan Bisharat
slack:arslanbisharat

**Comment by Ashah15** [comment]
This is the work of milestone2 where I created a component in the src and implemented the App, button, display, and buttonpanel for preparation of the app

**Review by BrittanyBlake — APPROVED** [review]
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****

 Good Luck and Happy Coding! 🍀 👩🏾‍💻

**Pull request merged**
