### PR TITLE
Milestone1

### PR DESCRIPTION
**Pull request by Ashah15**
This is the pull request for milestone1 in the react calculator app

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
## Hi @Ashah15  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**1. According to the pathwright instructions you need to  delete any unnecessary file or asset such as the `React svg Logo`, `app.test.js`, unnecessary code in `app.js`....**

image

**2. Kindly fix linter's error**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**

**Comment by Ashah15** [comment]
I made the necessary correction and fixed the error but for some reason, it still states that I have eslint error while in my terminal it does not state so.

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @Ashah15  :wave:

__I must commend your efforts so far in this project.__

__However, we need to ensure that all linter checks are passing before this project can be approved. Please check my comments below.__

**[ REQUIRED CHANGES ]**

- [ ] The ESlint error you're having says 
```
Configuration for rule "import/no-cycle" is invalid:
	Value "∞" should be integer.
```
To fix this error, follow the instructions below:
- Go to your linters.yml and replace line 19 with this line
```
npm install --save-dev eslint@7.11.x eslint-config-airbnb@18.1.x eslint-config-airbnb-base@14.2.0 eslint-plugin-import@2.20.x eslint-plugin-jsx-a11y@6.2.x eslint-plugin-react@7.20.x eslint-plugin-react-hooks@2.5.x babel-eslint@10.1.x
```

- If you're having it Locally:
You can fix it by doing 
```
npm -i --save-dev eslint-config-airbnb-base@14.2.0 or yarn add eslint-config-airbnb-base@14.2.0 --dev
```

**_Why:_**
The issue is caused by the eslint-config-airbnb-base changing Infinite to ∞ in node_modules/eslint-config-airbnb-base/rules/imports.js for some reason which causes this issue since whatever was using that file was expecting an integer but got ∞ instead

**[ OPTIONAL CHANGES ]**
N/A


* * *
**Please make the required changes and submit another review request when you are done.**

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**

**Always post your inquiries and questions on this PR thread as a comment. You can mention me (@teekaytech) so I can see your comments and respond.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by wathigo — APPROVED** [review]
## APPROVED :heavy_check_mark:  
Great job implementing the suggested changes.

**You may proceed to the next milestone.**

**Happy Coding :computer: 
Simon Wathigo**

**Pull request merged**
